# Generated by Django 2.2.6 on 2019-10-14 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='occurances',
            new_name='occurence',
        ),
    ]
