# Generated by Django 2.2.6 on 2019-10-14 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_auto_20191014_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='occurence',
            field=models.BigIntegerField(),
        ),
    ]
