# Generated by Django 2.2.6 on 2019-10-14 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0003_auto_20191014_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='text',
            field=models.CharField(max_length=50),
        ),
    ]
